services:
  app:
    image: app:latest
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
  
volumes:
  redis-data: {}