services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - first-nest-network

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    networks:
      - first-nest-network

networks:
  first-nest-network:
    external: true
  
volumes:
  redis-data: {}